import React from 'react'
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'

// Register a standard font
Font.register({
    family: 'Open Sans',
    src: 'https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0e.ttf'
})

const styles = StyleSheet.create({
    page: {
        fontFamily: 'Open Sans',
        padding: 30,
        backgroundColor: '#FFFFFF',
        color: '#333333'
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 40,
        borderBottomWidth: 2,
        borderBottomColor: '#EEEEEE',
        paddingBottom: 20
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1a1a1a'
    },
    subtitle: {
        fontSize: 12,
        color: '#666666',
        marginTop: 4
    },
    companyInfo: {
        textAlign: 'right'
    },
    section: {
        marginBottom: 20
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#4F46E5', // Brand color
        textTransform: 'uppercase'
    },
    summaryGrid: {
        flexDirection: 'row',
        marginBottom: 20,
        backgroundColor: '#F9FAFB',
        padding: 15,
        borderRadius: 4
    },
    summaryItem: {
        flex: 1,
        alignItems: 'center'
    },
    summaryLabel: {
        fontSize: 10,
        color: '#666666',
        marginBottom: 4
    },
    summaryValue: {
        fontSize: 18,
        fontWeight: 'bold'
    },
    table: {
        display: 'flex',
        width: 'auto',
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#EEEEEE',
        borderRightWidth: 0,
        borderBottomWidth: 0
    },
    tableRow: {
        margin: 'auto',
        flexDirection: 'row'
    },
    tableCol: {
        width: '25%',
        borderStyle: 'solid',
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderColor: '#EEEEEE'
    },
    tableHeader: {
        backgroundColor: '#F3F4F6',
        fontWeight: 'bold'
    },
    tableCell: {
        margin: 5,
        fontSize: 10
    }
})

interface ReportData {
    propertyName: string
    ownerName: string
    reportPeriod: string
    totalIncome: number
    totalExpenses: number
    netOperatingIncome: number
    transactions: Array<{
        date: string
        description: string
        category: string
        amount: number
        type: 'income' | 'expense'
    }>
}

export const ReportPDF = ({ data }: { data: ReportData }) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* Header */}
            <View style={styles.header}>
                <View>
                    <Text style={styles.title}>Owner Statement</Text>
                    <Text style={styles.subtitle}>{data.propertyName}</Text>
                </View>
                <View style={styles.companyInfo}>
                    <Text style={{ fontSize: 10, color: '#666' }}>Generated by</Text>
                    <Text style={{ fontSize: 12, fontWeight: 'bold' }}>PropAuto System</Text>
                    <Text style={{ fontSize: 10, color: '#666' }}>{data.reportPeriod}</Text>
                </View>
            </View>

            {/* Financial Summary */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Financial Summary</Text>
                <View style={styles.summaryGrid}>
                    <View style={styles.summaryItem}>
                        <Text style={styles.summaryLabel}>Total Income</Text>
                        <Text style={{ ...styles.summaryValue, color: '#10B981' }}>
                            ${data.totalIncome.toFixed(2)}
                        </Text>
                    </View>
                    <View style={styles.summaryItem}>
                        <Text style={styles.summaryLabel}>Total Expenses</Text>
                        <Text style={{ ...styles.summaryValue, color: '#EF4444' }}>
                            ${data.totalExpenses.toFixed(2)}
                        </Text>
                    </View>
                    <View style={styles.summaryItem}>
                        <Text style={styles.summaryLabel}>Net Operating Income</Text>
                        <Text style={{ ...styles.summaryValue, color: '#4F46E5' }}>
                            ${data.netOperatingIncome.toFixed(2)}
                        </Text>
                    </View>
                </View>
            </View>

            {/* Transactions Table */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Transaction Details</Text>
                <View style={styles.table}>

                    {/* Table Header */}
                    <View style={[styles.tableRow, styles.tableHeader]}>
                        <View style={{ ...styles.tableCol, width: '20%' }}>
                            <Text style={styles.tableCell}>Date</Text>
                        </View>
                        <View style={{ ...styles.tableCol, width: '40%' }}>
                            <Text style={styles.tableCell}>Description</Text>
                        </View>
                        <View style={{ ...styles.tableCol, width: '20%' }}>
                            <Text style={styles.tableCell}>Category</Text>
                        </View>
                        <View style={{ ...styles.tableCol, width: '20%' }}>
                            <Text style={styles.tableCell}>Amount</Text>
                        </View>
                    </View>

                    {/* Table Rows */}
                    {data.transactions.map((tx, i) => (
                        <View key={i} style={styles.tableRow}>
                            <View style={{ ...styles.tableCol, width: '20%' }}>
                                <Text style={styles.tableCell}>
                                    {new Date(tx.date).toLocaleDateString()}
                                </Text>
                            </View>
                            <View style={{ ...styles.tableCol, width: '40%' }}>
                                <Text style={styles.tableCell}>{tx.description}</Text>
                            </View>
                            <View style={{ ...styles.tableCol, width: '20%' }}>
                                <Text style={styles.tableCell}>{tx.category}</Text>
                            </View>
                            <View style={{ ...styles.tableCol, width: '20%' }}>
                                <Text style={{
                                    ...styles.tableCell,
                                    textAlign: 'right',
                                    color: tx.type === 'income' ? '#10B981' : '#EF4444'
                                }}>
                                    {tx.type === 'expense' ? '-' : ''}${tx.amount.toFixed(2)}
                                </Text>
                            </View>
                        </View>
                    ))}
                </View>
            </View>

            {/* Footer */}
            <View style={{ position: 'absolute', bottom: 30, left: 30, right: 30 }}>
                <Text style={{ fontSize: 10, color: '#999', textAlign: 'center' }}>
                    This report was automatically generated. For questions, please contact support.
                </Text>
            </View>

        </Page>
    </Document>
)
